version: "3.8"

services:
  php-fpm:
    container_name: product-php-fpm-8.1
    restart: "no"
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      depends_on:
        -postgres
    build:
      context: ./
      args:
        PUID: ${CONTAINER_UID}
        PGID: ${CONTAINER_GID}
    volumes:
      - ${PROJECT_DIR}:/app
    working_dir: /app
  db:
    container_name: product-db-postgresql
    image: postgres:latest
    restart: "no"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data:rw
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  nginx:
    image: nginx:stable
    container_name: product-nginx-server
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
      - ${PROJECT_DIR}:/app

