version: "3.9"

services:
  php-fpm:
    container_name: product-php-fpm-8.1
    restart: "no"
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG?}
      depends_on:
        -postgres
    build:
      context: ./
      args:
        PUID: ${CONTAINER_UID}
        PGID: ${CONTAINER_GID}
        SSH_KEY_NAME: ${SSH_KEY_NAME:-id_rsa}
    volumes:
      - ${PROJECT_DIR}:/app
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app
    secrets:
      - my_ssh_key
    expose:
      - 9000
  db:
    container_name: product-db-postgresql
    image: postgres:latest
    restart: "no"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data:rw
    volumes:
      - ../db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  nginx:
    image: nginx:stable
    container_name: product-nginx-server
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      - php-fpm
    volumes:
      - ../nginx/local.conf:/etc/nginx/conf.d/default.conf
      - ${PROJECT_DIR}:/app

  memcached:
    image: memcached:1.6
    ports:
      - "11211:11211"

secrets:
  my_ssh_key:
    file: ~/.ssh/${SSH_KEY_NAME:-id_rsa}
